spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  profiles:
    group:
      blue: "prod,blue"
      green: "prod,green"
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
server:
  env: ${APP_ENV:blue}

ai-server:
  base-url: ${AI_SERVER_BASE_URL:http://localhost:8000}
  timeout-seconds: ${AI_SERVER_TIMEOUT:30}

