spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  jpa:
    hibernate:
      ddl-auto: update

ai-server:
  base-url: ${AI_SERVER_BASE_URL:http://localhost:8000}
  timeout-seconds: ${AI_SERVER_TIMEOUT:30}

